theme: jekyll-theme-minimal
title: Avijit Thawani
description: avijit.thawani.cse14@iitbhu.ac.in
logo: https://lh4.googleusercontent.com/xfuQ6xm9KPlwAkv4taTqm-lJ58v6G2aQcjua3ZPE4XNH6GQ66YzU_5mgsC1fjYquDuadR821=w16383

