theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: ""
    values:
      title: Avijit Thawani
      description: avijit.thawani.cse14@iitbhu.ac.in
      logo: https://lh6.googleusercontent.com/plfq4ccPx-AAwuOKlihIAfN0MkoJGJHNqX1IPW0apKRBLUVWcQrvL1dNOnci5P56A_jdw5g=w16383

